export const LANGUAGE_STORAGE_KEY = "rigsync_language";
export const DEFAULT_LANGUAGE = "en";

const MESSAGES = {
  en: {
    langToggle: "AR",
    brandNavFeatures: "Features",
    brandNavAbout: "About Us",
    brandNavFaq: "FAQ",
    back: "Back",
    logout: "Logout",
    settings: "Settings",
    workspace: "RigSync Workspace",
    welcome: "Welcome",
    login: "Login",
    sessionActive: "Session already active",
    loginSubtitle: "Sign in to access the dashboard and operational workspace.",
    email: "Email",
    password: "Password",
    forgotPassword: "Forgot your password?",
    noAccount: "Don't have an account?",
    signUp: "Sign up",
    backHome: "Back to Home",
    loginFailed: "Login failed.",
    heroTitle: "Operational Precision at Scale",
    heroText: "Plan and execute rig moves with simulation-driven logistics and full operational visibility.",
    openWorkspace: "Open Workspace",
    digitizeNow: "Digitize Now",
    featuresTitle: "Features",
    featuresHeadline: "Operations software designed for move clarity",
    aboutTitle: "About Us",
    aboutHeadline: "Built for crews that need speed without losing control",
    aboutCopy: "RigSync keeps the dark, command-center visual language of the existing product while turning it into a scalable operational frontend. The experience is tuned for pre-move planning, confident dashboarding, and production-grade readability on desktop and tablet.",
    rigMovesTracked: "Rig moves tracked",
    savedOperationalRuns: "Saved operational runs",
    logicalLoads: "Logical loads",
    availableForPlanning: "Available for planning",
    routingMode: "Routing mode",
    liveFallback: "Live + fallback",
    resilientDefault: "Resilient by default",
    footerCopy: "Premium SaaS frontend for modern rig move operations, from planning through execution.",
    product: "Product",
    company: "Company",
    dashboard: "Dashboard",
    assignedRig: "Assigned Rig",
    rigDrillingOverview: "Rig Drilling Overview",
    currentSite: "Current site",
    assignedField: "Assigned field",
    currentWell: "Current well",
    drillingCompletion: "Drilling Completion",
    currentWellProgress: "Current well progress",
    reusableStock: "Reusable Stock",
    loadGroupsOnSite: "load groups on site",
    startupLoadsReady: "Startup Loads Ready",
    stillMissing: "still missing",
    fleetAvailable: "Fleet Available",
    managerTrucksFree: "Manager trucks free to assign",
    neededLoadsOnSite: "Needed Loads On Site",
    cancel: "Cancel",
    saveLoads: "Save Loads",
    editLoads: "Edit Loads",
    reusableLoadsAdjust: "Only reusable needed loads can be adjusted here. Permanent rig loads stay read-only.",
    editable: "Editable",
    onSite: "on site",
    truck: "Truck",
    needed: "Needed",
    countOnSite: "Count On Site",
    availableToTransfer: "Available To Transfer",
    planned: "Planned",
    noReusableLoads: "No reusable needed loads are configured for this rig.",
    currentRigMove: "Current Rig Move",
    execution: "Execution",
    completion: "Completion",
    managerView: "Manager view",
    supervisor: "Supervisor",
    managerOverview: "Manager Overview",
    rigOperations: "rig operations",
    managerOverviewCopy: "Live operations, ready trucks, and driver accounts in one view.",
    drillingRigs: "Drilling Rigs",
    alreadyOperating: "Already operating",
    movingRigs: "Moving Rigs",
    executingNow: "Executing now",
    planningRigs: "Planning Rigs",
    stillPlanning: "Still in planning",
    totalLoads: "Total Loads",
    acrossAllMoves: "Across all moves",
    driversReady: "Drivers Ready",
    driverAccounts: "driver accounts",
    driverCapacity: "Driver Capacity",
    currentlyAllocated: "currently allocated",
    activeDrivers: "Active Drivers",
    linkedToLiveTasks: "Linked to live tasks",
    foremenActive: "Foremen Active",
    totalForemen: "total foremen",
    resources: "Resources",
    trucksReady: "trucks ready",
    resourcesCopy: "Create driver accounts only. Each driver carries one truck type, and the planner uses that as the truck assigned to the driver.",
    closeDriver: "Close Driver",
    addDriver: "Add Driver",
    availableDrivers: "Available Drivers",
    tasksWaiting: "Tasks Waiting",
    driverAppSyncTarget: "Driver app sync target",
    driverName: "Driver name",
    remove: "Remove",
    assigned: "Assigned",
    available: "Available",
    liveTask: "Live task",
    taskObject: "Task object",
    driverTruck: "Driver truck",
    currentTrip: "Current Trip",
    moreTripsQueued: "more trips queued after this one.",
    assignedTrips: "Assigned Trips",
    driverOverview: "Driver Overview",
    activeTasks: "active tasks",
    completeAssignedTask: "Complete each assigned task in order: rig down, rig move, then rig up.",
    rigDown: "Rig Down",
    rigMove: "Rig Move",
    rigUp: "Rig Up",
    completed: "Completed",
    queued: "Queued",
    route: "Route",
    pending: "Pending",
    done: "Done",
    noAssignedTrips: "No assigned trips yet. Trips will appear after a foreman starts execution.",
    timePassed: "Time Passed",
    planByNow: "Plan By Now",
    nextTask: "Next Task",
    executionTracking: "Execution Tracking",
    actualVsPlanned: "Actual vs Planned",
    aheadBehind: "Ahead / Behind",
    timeLeft: "Time Left",
    driversAssigned: "Drivers Assigned",
    tasksDone: "Tasks Done",
    stageTasksDone: "Stage Tasks Done",
    plannedTasksByNow: "Planned Tasks By Now",
    plannedTasks: "Planned Tasks",
    executionPlan: "Execution Plan",
    customExecutionPlan: "Custom Execution Plan",
    planOverview: "Plan Overview",
    totalTime: "Total Time",
    roundTrips: "Round Trips",
    planCost: "Plan Cost",
    criticalPath: "Critical Path",
    homeHeroTitleLine1: "Operational",
    homeHeroTitleAccent: "Precision",
    homeHeroTitleLine2: "At Scale",
    homeHeroBody: "Plan and execute rig moves through one connected operational network. RigSync links rigs, routes, trucks, and field decisions in a live visual system that moves with the page like an interactive control surface.",
    homeAboutBadge: "About RigSync",
    homeAboutTitle: "A Digital Twin Built For Real Rig Move Decisions",
    homeAboutBody: "RigSync gives drilling organizations a digital twin of their move operations. Instead of coordinating rig moves through disconnected spreadsheets, phone calls, and isolated tracking tools, teams can model rigs, trucks, drivers, routes, resources, and site readiness in one operational system. The result is faster planning, clearer trade-offs, stronger execution visibility, and better control from the office to the field.",
    homeMetricConnectedRigsLabel: "Connected Rigs",
    homeMetricConnectedRigsMeta: "Across the company network",
    homeMetricMoveScenariosLabel: "Move Scenarios",
    homeMetricMoveScenariosMeta: "Speed, cost, and utilization trade-offs",
    homeMetricTrackedResourcesLabel: "Tracked Resources",
    homeMetricTrackedResourcesLoadingMeta: "Loading live operational totals",
    homeMetricTrackedResourcesMeta: "Drivers, trucks, loads, and readiness signals",
    homeMetricExecutionViewsLabel: "Execution Views",
    homeMetricExecutionViewsMeta: "Planning, move tracking, oversight, and AI assistance",
    homeFeaturesTitle: "From Move Planning To Fleet Oversight In One System",
    homeFeaturesLead: "RigSync combines planning, execution, fleet visibility, and field readiness in one operational system built for live rig move control.",
    homeFeaturePlanningTitle: "Network-Based Rig Planning",
    homeFeaturePlanningCopy: "See the company fleet as one connected operational network, choose the rig that needs to move, and plan in the context of all available rigs, routes, trucks, and field constraints.",
    homeFeatureOptimizationTitle: "Trade-Off Aware Optimization",
    homeFeatureOptimizationCopy: "Compare the best move plan for speed, cost, or utilization. RigSync surfaces the operational trade-offs clearly so the selected plan matches the situation on the ground.",
    homeFeatureExecutionTitle: "Digital Twin Execution View",
    homeFeatureExecutionCopy: "Move from planning into execution on the same operational twin. Follow route progress, move phases, active trucks, and site readiness without switching between disconnected tools.",
    homeFeatureOversightTitle: "Office-Level Fleet Oversight",
    homeFeatureOversightCopy: "Oversee all rigs, active moves, drivers, trucks, and field resources from one control surface designed for management visibility across the full company network.",
    homeFeatureResourcesTitle: "Resource And Driver Control",
    homeFeatureResourcesCopy: "Manage truck readiness, linked drivers, fleet availability, and operational assignments through one workspace that stays aligned with move execution.",
    homeFeatureAssistantTitle: "AI Operational Assistant",
    homeFeatureAssistantCopy: "Use the assistant to retrieve move status, inspect plan trade-offs, support senior review, and answer operational questions quickly with the right context already in the system.",
    homeFaqTitle: "Digital Twin Questions That Matter",
    homeFaq1Question: "What is the difference between a digital twin and a simulation?",
    homeFaq1Answer: "A simulation tests one possible move scenario. A digital twin is broader: it represents the live operational system itself, including rigs, trucks, drivers, routes, resources, and move status. In RigSync, simulation is one capability inside the digital twin.",
    homeFaq2Question: "Why should I use RigSync instead of traditional planning tools?",
    homeFaq2Answer: "Traditional move planning is usually fragmented across spreadsheets, calls, static plans, and separate tracking tools. RigSync brings planning, comparison, execution visibility, office oversight, and operational intelligence into one connected platform.",
    homeFaq3Question: "How does RigSync help decisions during a move?",
    homeFaq3Answer: "RigSync helps teams choose the plan that best fits current priorities, whether that means moving faster, reducing cost, or improving truck utilization. During execution it keeps managers, foremen, and field teams aligned on one operational picture.",
    homeFooterBody: "A digital twin platform for network-wide rig move planning, execution oversight, and operational intelligence.",
    homeFooterTagline: "Built for digital twin rig move operations",
  },
  ar: {
    langToggle: "EN",
    brandNavFeatures: "المزايا",
    brandNavAbout: "من نحن",
    brandNavFaq: "الأسئلة الشائعة",
    back: "رجوع",
    logout: "تسجيل الخروج",
    settings: "الإعدادات",
    workspace: "مساحة عمل RigSync",
    welcome: "مرحباً",
    login: "تسجيل الدخول",
    sessionActive: "الجلسة مفعلة بالفعل",
    loginSubtitle: "سجّل الدخول للوصول إلى لوحة التحكم ومساحة التشغيل.",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    forgotPassword: "هل نسيت كلمة المرور؟",
    noAccount: "ليس لديك حساب؟",
    signUp: "إنشاء حساب",
    backHome: "العودة للرئيسية",
    loginFailed: "فشل تسجيل الدخول.",
    heroTitle: "دقة تشغيلية على نطاق واسع",
    heroText: "خطط ونفذ نقلات الحفارات عبر لوجستيات مدفوعة بالمحاكاة ورؤية تشغيلية كاملة.",
    openWorkspace: "فتح مساحة العمل",
    digitizeNow: "ابدأ الرقمنة",
    featuresTitle: "المزايا",
    featuresHeadline: "برنامج عمليات مصمم لوضوح النقل",
    aboutTitle: "من نحن",
    aboutHeadline: "مصمم للفرق التي تحتاج السرعة دون فقدان السيطرة",
    aboutCopy: "يحافظ RigSync على اللغة البصرية الداكنة لمركز القيادة في المنتج الحالي مع تحويله إلى واجهة تشغيلية قابلة للتوسع. التجربة مهيأة للتخطيط قبل النقل ولوحات متابعة واضحة وقراءة موثوقة على سطح المكتب والجهاز اللوحي.",
    rigMovesTracked: "نقلات حفارات متتبعة",
    savedOperationalRuns: "تشغيلات محفوظة",
    logicalLoads: "الأحمال المنطقية",
    availableForPlanning: "متاحة للتخطيط",
    routingMode: "وضع المسار",
    liveFallback: "حي + بديل",
    resilientDefault: "مرن افتراضياً",
    footerCopy: "واجهة SaaS متميزة لعمليات نقل الحفارات الحديثة من التخطيط حتى التنفيذ.",
    product: "المنتج",
    company: "الشركة",
    dashboard: "لوحة التحكم",
    assignedRig: "الحفارة المخصصة",
    rigDrillingOverview: "نظرة عامة على الحفارة",
    currentSite: "الموقع الحالي",
    assignedField: "الحقل المخصص",
    currentWell: "البئر الحالي",
    drillingCompletion: "نسبة الحفر",
    currentWellProgress: "تقدم البئر الحالي",
    reusableStock: "المخزون القابل لإعادة الاستخدام",
    loadGroupsOnSite: "مجموعات أحمال في الموقع",
    startupLoadsReady: "أحمال البدء الجاهزة",
    stillMissing: "ما زال مفقوداً",
    fleetAvailable: "الأسطول المتاح",
    managerTrucksFree: "شاحنات المدير المتاحة للتخصيص",
    neededLoadsOnSite: "الأحمال المطلوبة في الموقع",
    cancel: "إلغاء",
    saveLoads: "حفظ الأحمال",
    editLoads: "تعديل الأحمال",
    reusableLoadsAdjust: "يمكن تعديل الأحمال المطلوبة القابلة لإعادة الاستخدام فقط هنا. أحمال الحفارة الدائمة تبقى للقراءة فقط.",
    editable: "قابل للتعديل",
    onSite: "في الموقع",
    truck: "الشاحنة",
    needed: "المطلوب",
    countOnSite: "العدد في الموقع",
    availableToTransfer: "المتاح للنقل",
    planned: "مخطط",
    noReusableLoads: "لا توجد أحمال مطلوبة قابلة لإعادة الاستخدام لهذه الحفارة.",
    currentRigMove: "نقلة الحفارة الحالية",
    execution: "التنفيذ",
    completion: "الإنجاز",
    managerView: "عرض المدير",
    supervisor: "المشرف",
    managerOverview: "نظرة عامة للمدير",
    rigOperations: "عمليات حفارات",
    managerOverviewCopy: "العمليات الحية والشاحنات الجاهزة وحسابات السائقين في شاشة واحدة.",
    drillingRigs: "حفارات في الحفر",
    alreadyOperating: "تعمل حالياً",
    movingRigs: "حفارات تتحرك",
    executingNow: "قيد التنفيذ الآن",
    planningRigs: "حفارات في التخطيط",
    stillPlanning: "ما زالت في التخطيط",
    totalLoads: "إجمالي الأحمال",
    acrossAllMoves: "عبر جميع النقلات",
    driversReady: "السائقون الجاهزون",
    driverAccounts: "حسابات سائقين",
    driverCapacity: "سعة السائقين",
    currentlyAllocated: "مخصصة حالياً",
    activeDrivers: "السائقون النشطون",
    linkedToLiveTasks: "مرتبطون بمهام حية",
    foremenActive: "الفورمن النشطون",
    totalForemen: "إجمالي الفورمن",
    resources: "الموارد",
    trucksReady: "شاحنات جاهزة",
    resourcesCopy: "أنشئ حسابات السائقين فقط. كل سائق يحمل نوع شاحنته، ويستخدم المخطط ذلك كشاحنة مخصصة للسائق.",
    closeDriver: "إغلاق السائق",
    addDriver: "إضافة سائق",
    availableDrivers: "السائقون المتاحون",
    tasksWaiting: "المهام المنتظرة",
    driverAppSyncTarget: "هدف مزامنة تطبيق السائق",
    driverName: "اسم السائق",
    remove: "إزالة",
    assigned: "مخصص",
    available: "متاح",
    liveTask: "مهمة حية",
    taskObject: "كائن المهمة",
    driverTruck: "شاحنة السائق",
    currentTrip: "الرحلة الحالية",
    moreTripsQueued: "رحلات أخرى في الانتظار بعد هذه الرحلة.",
    assignedTrips: "الرحلات المخصصة",
    driverOverview: "نظرة عامة للسائق",
    activeTasks: "مهام نشطة",
    completeAssignedTask: "أكمل كل مهمة مخصصة بالترتيب: فك الحفارة ثم النقل ثم التركيب.",
    rigDown: "فك الحفارة",
    rigMove: "نقل الحفارة",
    rigUp: "تركيب الحفارة",
    completed: "مكتمل",
    queued: "في الانتظار",
    route: "المسار",
    pending: "قيد الانتظار",
    done: "تم",
    noAssignedTrips: "لا توجد رحلات مخصصة بعد. ستظهر الرحلات بعد أن يبدأ الفورمن التنفيذ.",
    timePassed: "الوقت المنقضي",
    planByNow: "المخطط حتى الآن",
    nextTask: "المهمة التالية",
    executionTracking: "متابعة التنفيذ",
    actualVsPlanned: "الفعلي مقابل المخطط",
    aheadBehind: "متقدم / متأخر",
    timeLeft: "الوقت المتبقي",
    driversAssigned: "السائقون المخصصون",
    tasksDone: "المهام المنجزة",
    stageTasksDone: "مهام المراحل المنجزة",
    plannedTasksByNow: "المهام المخططة حتى الآن",
    plannedTasks: "المهام المخططة",
    executionPlan: "خطة التنفيذ",
    customExecutionPlan: "خطة تنفيذ مخصصة",
    planOverview: "نظرة عامة على الخطة",
    totalTime: "إجمالي الوقت",
    roundTrips: "الرحلات",
    planCost: "تكلفة الخطة",
    criticalPath: "المسار الحرج",
    homeHeroTitleLine1: "الدقة التشغيلية",
    homeHeroTitleAccent: "المحكمة",
    homeHeroTitleLine2: "على نطاق واسع",
    homeHeroBody: "خطط ونفذ نقلات الحفارات عبر شبكة تشغيلية مترابطة واحدة. يربط RigSync الحفارات والمسارات والشاحنات وقرارات الميدان داخل نظام بصري حي يتحرك مع الصفحة مثل سطح تحكم تفاعلي.",
    homeAboutBadge: "عن RigSync",
    homeAboutTitle: "توأم رقمي مبني لقرارات نقل الحفارات الحقيقية",
    homeAboutBody: "يمنح RigSync شركات الحفر توأماً رقمياً لعمليات نقلها. بدلاً من تنسيق النقلات عبر جداول منفصلة واتصالات هاتفية وأدوات متابعة معزولة، يمكن للفرق نمذجة الحفارات والشاحنات والسائقين والمسارات والموارد وجاهزية الموقع داخل نظام تشغيلي واحد. النتيجة هي تخطيط أسرع ومفاضلات أوضح ورؤية تنفيذ أقوى وتحكم أفضل من المكتب إلى الميدان.",
    homeMetricConnectedRigsLabel: "حفارات مترابطة",
    homeMetricConnectedRigsMeta: "عبر شبكة الشركة",
    homeMetricMoveScenariosLabel: "سيناريوهات النقل",
    homeMetricMoveScenariosMeta: "مفاضلات السرعة والتكلفة والاستغلال",
    homeMetricTrackedResourcesLabel: "موارد متتبعة",
    homeMetricTrackedResourcesLoadingMeta: "جارٍ تحميل الإجماليات التشغيلية الحية",
    homeMetricTrackedResourcesMeta: "السائقون والشاحنات والأحمال وإشارات الجاهزية",
    homeMetricExecutionViewsLabel: "واجهات التنفيذ",
    homeMetricExecutionViewsMeta: "التخطيط وتتبع النقل والإشراف والمساعدة الذكية",
    homeFeaturesTitle: "من تخطيط النقلة إلى الإشراف على الأسطول في نظام واحد",
    homeFeaturesLead: "يجمع RigSync التخطيط والتنفيذ ورؤية الأسطول وجاهزية الميدان داخل نظام تشغيلي واحد مبني للتحكم الحي في نقل الحفارات.",
    homeFeaturePlanningTitle: "تخطيط الحفارات عبر الشبكة",
    homeFeaturePlanningCopy: "اعرض أسطول الشركة كشبكة تشغيلية مترابطة واحدة، واختر الحفارة التي تحتاج إلى النقل، وخطط ضمن سياق الحفارات والمسارات والشاحنات والقيود الميدانية المتاحة.",
    homeFeatureOptimizationTitle: "تحسين واعٍ بالمفاضلات",
    homeFeatureOptimizationCopy: "قارن أفضل خطة نقل من حيث السرعة أو التكلفة أو الاستغلال. يعرض RigSync المفاضلات التشغيلية بوضوح حتى تتوافق الخطة المختارة مع الواقع الميداني.",
    homeFeatureExecutionTitle: "واجهة تنفيذ التوأم الرقمي",
    homeFeatureExecutionCopy: "انتقل من التخطيط إلى التنفيذ على نفس التوأم التشغيلي. تابع تقدم المسار ومراحل النقلة والشاحنات النشطة وجاهزية الموقع دون التنقل بين أدوات منفصلة.",
    homeFeatureOversightTitle: "إشراف مكتبي على مستوى الأسطول",
    homeFeatureOversightCopy: "أشرف على جميع الحفارات والنقلات النشطة والسائقين والشاحنات والموارد الميدانية من سطح تحكم واحد مصمم لإظهار رؤية الإدارة عبر شبكة الشركة كاملة.",
    homeFeatureResourcesTitle: "التحكم في الموارد والسائقين",
    homeFeatureResourcesCopy: "أدر جاهزية الشاحنات والسائقين المرتبطين وتوفر الأسطول والتكليفات التشغيلية من خلال مساحة عمل واحدة تبقى متوافقة مع تنفيذ النقلة.",
    homeFeatureAssistantTitle: "مساعد تشغيلي بالذكاء الاصطناعي",
    homeFeatureAssistantCopy: "استخدم المساعد لاسترجاع حالة النقلة ومراجعة مفاضلات الخطط ودعم المراجعة العليا والإجابة بسرعة عن الأسئلة التشغيلية مع وجود السياق الصحيح داخل النظام.",
    homeFaqTitle: "أسئلة التوأم الرقمي المهمة",
    homeFaq1Question: "ما الفرق بين التوأم الرقمي والمحاكاة؟",
    homeFaq1Answer: "المحاكاة تختبر سيناريو نقل واحداً محتملاً. أما التوأم الرقمي فهو أوسع، إذ يمثل النظام التشغيلي الحي نفسه بما يشمل الحفارات والشاحنات والسائقين والمسارات والموارد وحالة النقلة. في RigSync تمثل المحاكاة قدرة واحدة داخل التوأم الرقمي.",
    homeFaq2Question: "لماذا أستخدم RigSync بدلاً من أدوات التخطيط التقليدية؟",
    homeFaq2Answer: "غالباً ما يكون تخطيط نقل الحفارات التقليدي مجزأً بين الجداول والاتصالات والخطط الثابتة وأدوات التتبع المنفصلة. يجمع RigSync التخطيط والمقارنة ورؤية التنفيذ والإشراف المكتبي والذكاء التشغيلي في منصة مترابطة واحدة.",
    homeFaq3Question: "كيف يساعد RigSync في القرارات أثناء النقلة؟",
    homeFaq3Answer: "يساعد RigSync الفرق على اختيار الخطة الأنسب للأولوية الحالية، سواء كانت السرعة أو خفض التكلفة أو تحسين استغلال الشاحنات. وأثناء التنفيذ يحافظ على توافق المديرين والفورمن وفرق الميدان على صورة تشغيلية واحدة.",
    homeFooterBody: "منصة توأم رقمي لتخطيط نقل الحفارات على مستوى الشبكة، والإشراف على التنفيذ، والذكاء التشغيلي.",
    homeFooterTagline: "مبني لعمليات نقل الحفارات بالتوأم الرقمي",
  },
};

export function getLanguageDirection(language = DEFAULT_LANGUAGE) {
  return language === "ar" ? "rtl" : "ltr";
}

export function translate(language = DEFAULT_LANGUAGE, key, fallback = "") {
  return MESSAGES[language]?.[key] || MESSAGES[DEFAULT_LANGUAGE]?.[key] || fallback || key;
}
