export const LANGUAGE_STORAGE_KEY = "rigsync_language";
export const DEFAULT_LANGUAGE = "en";

const en = {
  langToggle: "AR",
  brandNavFeatures: "Features",
  brandNavAbout: "About Us",
  brandNavFaq: "FAQ",
  back: "Back",
  logout: "Logout",
  settings: "Settings",
  workspace: "RigSync Workspace",
  welcome: "Welcome",
  login: "Login",
  sessionActive: "Session already active",
  loginSubtitle: "Sign in to access the dashboard and operational workspace.",
  email: "Email",
  password: "Password",
  forgotPassword: "Forgot your password?",
  noAccount: "Don't have an account?",
  signUp: "Sign up",
  backHome: "Back to Home",
  loginFailed: "Login failed.",
  heroTitle: "Operational Precision at Scale",
  heroText: "Plan and execute rig moves with simulation-driven logistics and full operational visibility.",
  openWorkspace: "Open Workspace",
  digitizeNow: "Digitize Now",
  featuresTitle: "Features",
  featuresHeadline: "Operations software designed for move clarity",
  aboutTitle: "About Us",
  aboutHeadline: "Built for crews that need speed without losing control",
  aboutCopy: "RigSync keeps the dark, command-center visual language of the existing product while turning it into a scalable operational frontend. The experience is tuned for pre-move planning, confident dashboarding, and production-grade readability on desktop and tablet.",
  rigMovesTracked: "Rig moves tracked",
  savedOperationalRuns: "Saved operational runs",
  logicalLoads: "Logical loads",
  availableForPlanning: "Available for planning",
  routingMode: "Routing mode",
  liveFallback: "Live + fallback",
  resilientDefault: "Resilient by default",
  footerCopy: "Premium SaaS frontend for modern rig move operations, from planning through execution.",
  product: "Product",
  company: "Company",
  dashboard: "Dashboard",
  assignedRig: "Assigned Rig",
  rigDrillingOverview: "Rig Drilling Overview",
  currentSite: "Current site",
  assignedField: "Assigned field",
  currentWell: "Current well",
  drillingCompletion: "Drilling Completion",
  currentWellProgress: "Current well progress",
  reusableStock: "Reusable Stock",
  loadGroupsOnSite: "load groups on site",
  startupLoadsReady: "Startup Loads Ready",
  stillMissing: "still missing",
  fleetAvailable: "Fleet Available",
  managerTrucksFree: "Manager trucks free to assign",
  neededLoadsOnSite: "Needed Loads On Site",
  cancel: "Cancel",
  saveLoads: "Save Loads",
  editLoads: "Edit Loads",
  reusableLoadsAdjust: "Only reusable needed loads can be adjusted here. Permanent rig loads stay read-only.",
  editable: "Editable",
  onSite: "on site",
  truck: "Truck",
  needed: "Needed",
  countOnSite: "Count On Site",
  availableToTransfer: "Available To Transfer",
  planned: "Planned",
  noReusableLoads: "No reusable needed loads are configured for this rig.",
  currentRigMove: "Current Rig Move",
  execution: "Execution",
  completion: "Completion",
  managerView: "Manager view",
  supervisor: "Supervisor",
  managerOverview: "Manager Overview",
  rigOperations: "rig operations",
  managerOverviewCopy: "Live operations, ready trucks, and driver accounts in one view.",
  drillingRigs: "Drilling Rigs",
  alreadyOperating: "Already operating",
  movingRigs: "Moving Rigs",
  executingNow: "Executing now",
  planningRigs: "Planning Rigs",
  stillPlanning: "Still in planning",
  totalLoads: "Total Loads",
  acrossAllMoves: "Across all moves",
  driversReady: "Drivers Ready",
  driverAccounts: "driver accounts",
  driverCapacity: "Driver Capacity",
  currentlyAllocated: "currently allocated",
  activeDrivers: "Active Drivers",
  linkedToLiveTasks: "Linked to live tasks",
  foremenActive: "Foremen Active",
  totalForemen: "total foremen",
  resources: "Resources",
  trucksReady: "trucks ready",
  resourcesCopy: "Create driver accounts only. Each driver carries one truck type, and the planner uses that as the truck assigned to the driver.",
  closeDriver: "Close Driver",
  addDriver: "Add Driver",
  availableDrivers: "Available Drivers",
  tasksWaiting: "Tasks Waiting",
  driverAppSyncTarget: "Driver app sync target",
  driverName: "Driver name",
  remove: "Remove",
  assigned: "Assigned",
  available: "Available",
  liveTask: "Live task",
  taskObject: "Task object",
  driverTruck: "Driver truck",
  currentTrip: "Current Trip",
  moreTripsQueued: "more trips queued after this one.",
  assignedTrips: "Assigned Trips",
  driverOverview: "Driver Overview",
  activeTasks: "active tasks",
  completeAssignedTask: "Complete each assigned task in order: rig down, rig move, then rig up.",
  rigDown: "Rig Down",
  rigMove: "Rig Move",
  rigUp: "Rig Up",
  completed: "Completed",
  queued: "Queued",
  route: "Route",
  pending: "Pending",
  done: "Done",
  noAssignedTrips: "No assigned trips yet. Trips will appear after a foreman starts execution.",
  timePassed: "Time Passed",
  planByNow: "Plan By Now",
  nextTask: "Next Task",
  executionTracking: "Execution Tracking",
  actualVsPlanned: "Actual vs Planned",
  aheadBehind: "Ahead / Behind",
  timeLeft: "Time Left",
  driversAssigned: "Drivers Assigned",
  tasksDone: "Tasks Done",
  stageTasksDone: "Stage Tasks Done",
  plannedTasksByNow: "Planned Tasks By Now",
  plannedTasks: "Planned Tasks",
  executionPlan: "Execution Plan",
  customExecutionPlan: "Custom Execution Plan",
  planOverview: "Plan Overview",
  totalTime: "Total Time",
  roundTrips: "Round Trips",
  planCost: "Plan Cost",
  criticalPath: "Critical Path",
  homeHeroTitleLine1: "Operational",
  homeHeroTitleAccent: "Precision",
  homeHeroTitleLine2: "At Scale",
  homeHeroBody: "Plan and execute rig moves through one connected operational network. RigSync links rigs, routes, trucks, and field decisions in a live visual system that moves with the page like an interactive control surface.",
  homeAboutBadge: "About RigSync",
  homeAboutTitle: "A Digital Twin Built For Real Rig Move Decisions",
  homeAboutBody: "RigSync gives drilling organizations a digital twin of their move operations. Instead of coordinating rig moves through disconnected spreadsheets, phone calls, and isolated tracking tools, teams can model rigs, trucks, drivers, routes, resources, and site readiness in one operational system. The result is faster planning, clearer trade-offs, stronger execution visibility, and better control from the office to the field.",
  homeMetricConnectedRigsLabel: "Connected Rigs",
  homeMetricConnectedRigsMeta: "Across the company network",
  homeMetricMoveScenariosLabel: "Move Scenarios",
  homeMetricMoveScenariosMeta: "Speed, cost, and utilization trade-offs",
  homeMetricTrackedResourcesLabel: "Tracked Resources",
  homeMetricTrackedResourcesLoadingMeta: "Loading live operational totals",
  homeMetricTrackedResourcesMeta: "Drivers, trucks, loads, and readiness signals",
  homeMetricExecutionViewsLabel: "Execution Views",
  homeMetricExecutionViewsMeta: "Planning, move tracking, oversight, and AI assistance",
  homeFeaturesTitle: "From Move Planning To Fleet Oversight In One System",
  homeFeaturesLead: "RigSync combines planning, execution, fleet visibility, and field readiness in one operational system built for live rig move control.",
  homeFeaturePlanningTitle: "Network-Based Rig Planning",
  homeFeaturePlanningCopy: "See the company fleet as one connected operational network, choose the rig that needs to move, and plan in the context of all available rigs, routes, trucks, and field constraints.",
  homeFeatureOptimizationTitle: "Trade-Off Aware Optimization",
  homeFeatureOptimizationCopy: "Compare the best move plan for speed, cost, or utilization. RigSync surfaces the operational trade-offs clearly so the selected plan matches the situation on the ground.",
  homeFeatureExecutionTitle: "Digital Twin Execution View",
  homeFeatureExecutionCopy: "Move from planning into execution on the same operational twin. Follow route progress, move phases, active trucks, and site readiness without switching between disconnected tools.",
  homeFeatureOversightTitle: "Office-Level Fleet Oversight",
  homeFeatureOversightCopy: "Oversee all rigs, active moves, drivers, trucks, and field resources from one control surface designed for management visibility across the full company network.",
  homeFeatureResourcesTitle: "Resource And Driver Control",
  homeFeatureResourcesCopy: "Manage truck readiness, linked drivers, fleet availability, and operational assignments through one workspace that stays aligned with move execution.",
  homeFeatureAssistantTitle: "AI Operational Assistant",
  homeFeatureAssistantCopy: "Use the assistant to retrieve move status, inspect plan trade-offs, support senior review, and answer operational questions quickly with the right context already in the system.",
  homeFaqTitle: "Digital Twin Questions That Matter",
  homeFaq1Question: "What is the difference between a digital twin and a simulation?",
  homeFaq1Answer: "A simulation tests one possible move scenario. A digital twin is broader: it represents the live operational system itself, including rigs, trucks, drivers, routes, resources, and move status. In RigSync, simulation is one capability inside the digital twin.",
  homeFaq2Question: "Why should I use RigSync instead of traditional planning tools?",
  homeFaq2Answer: "Traditional move planning is usually fragmented across spreadsheets, calls, static plans, and separate tracking tools. RigSync brings planning, comparison, execution visibility, office oversight, and operational intelligence into one connected platform.",
  homeFaq3Question: "How does RigSync help decisions during a move?",
  homeFaq3Answer: "RigSync helps teams choose the plan that best fits current priorities, whether that means moving faster, reducing cost, or improving truck utilization. During execution it keeps managers, foremen, and field teams aligned on one operational picture.",
  homeFooterBody: "A digital twin platform for network-wide rig move planning, execution oversight, and operational intelligence.",
  homeFooterTagline: "Built for digital twin rig move operations",
  allRigs: "All Rigs",
  arrivalLockedOutbound: "Arrival stays locked until the live sensor reaches 100%.",
  arrivalLockedReturn: "Arrival stays locked until the live sensor reaches 100%.",
  arrived: "Arrived",
  arrivedSource: "Arrived at Source",
  assignedTrip: "Assigned trip",
  averageCompletion: "Average Completion",
  close: "Close",
  closedDriverTasks: "Closed driver tasks",
  completedTasks: "Completed Tasks",
  delayMinutesToday: "Delay Minutes Today",
  delayReason: "Delay reason",
  delayReasonNeeded: "Delay reason required",
  delayReasonPlaceholder: "Traffic, rig issue, weather, loading delay...",
  delayReasonPrompt: "Add a reason if this phase is running late.",
  delayReasonPromptDemo: "Add a reason if this phase is running late in the live demo.",
  delayReasonRequired: "Enter a delay reason once the phase is more than 20 minutes late.",
  delayReasonRequiredDemo: "Enter a delay reason once the phase is more than 20 seconds late.",
  destination: "Destination",
  drilling: "Drilling",
  driver: "Driver",
  driverMoveComplete: "Return trip completed.",
  driverMoveOutbound: "Truck is on the outbound trip to the rig.",
  driverMoveReadyReturn: "Truck arrived at the rig. Start the return as soon as the load is dropped.",
  driverMoveReturning: "Truck is returning to source. Confirm arrival only when it is back at source.",
  driverMoveWaitingStart: "Truck is parked at source. Start the move when the driver leaves.",
  driverReadiness: "Driver Readiness",
  driverReturnRunning: "Empty truck is returning to source. Confirm arrival only when it is really back at source.",
  driverReturnWaitingStart: "Empty truck is parked at destination. Start return when the driver leaves.",
  driverTasks: "Driver tasks",
  eta: "ETA",
  fleetReady: "Fleet Ready",
  futureStepsLocked: "Next steps stay locked until the current step is finished.",
  inDrilling: "In Drilling",
  late: "late",
  lateBy: "Late By",
  left: "left",
  liveTracking: "Live Tracking",
  loadTransfers: "Load Transfers",
  loads: "Loads",
  locked: "Locked",
  managerNetwork: "Manager Network",
  managerPlanOverview: "Manager Plan Overview",
  min: "min",
  move: "Move",
  networkSummary: "Network Summary",
  noRigSelected: "No rig selected",
  noRigSelectedCopy: "Select a rig on the map to inspect its live state, routing readiness, and transfer status.",
  noRigSelectedCopy3d: "Select a rig in the 3D view to inspect its live state, routing readiness, and transfer status.",
  pausedVsPlan: "Paused vs Plan",
  phaseEta: "Phase ETA",
  planWindow: "Plan Window",
  planning: "Planning",
  progress: "Progress",
  readyForDispatch: "Ready for Dispatch",
  readyToFinish: "Ready to finish",
  readyToTransport: "Ready to transport",
  rigOnSite: "Rig on site",
  rigOnSiteCopy: "The destination rig is already on site and not actively moving.",
  rigsLive: "Rigs Live",
  routeReady: "Route ready",
  routeReadyCopy: "The route is prepared and the rig is ready for transfer.",
  routesTracked: "Routes Tracked",
  selectedRig: "Selected Rig",
  sensor: "Sensor",
  source: "Source",
  startMoving: "Start Moving",
  startReturn: "Start Return",
  status: "Status",
  taskCompletion: "Task Completion",
  totalRigs: "Total Rigs",
  transferInMotion: "Transfer in motion",
  transferInMotionCopy: "This rig is actively being transferred right now.",
  transferLoad: "Transfer load",
  trip: "Trip",
  truckType: "Truck type",
  trucksFreeToAssign: "Trucks free to assign",
  viewAll: "View All",
  waitingOnFirstStage: "Waiting on first stage",
};

const ar = {
  langToggle: "EN",
  brandNavFeatures: "المزايا",
  brandNavAbout: "من نحن",
  brandNavFaq: "الأسئلة الشائعة",
  back: "رجوع",
  logout: "تسجيل الخروج",
  settings: "الإعدادات",
  workspace: "مساحة عمل RigSync",
  welcome: "مرحباً",
  login: "تسجيل الدخول",
  sessionActive: "الجلسة مفعلة بالفعل",
  loginSubtitle: "سجّل الدخول للوصول إلى لوحة التحكم ومساحة التشغيل.",
  email: "البريد الإلكتروني",
  password: "كلمة المرور",
  forgotPassword: "هل نسيت كلمة المرور؟",
  noAccount: "ليس لديك حساب؟",
  signUp: "إنشاء حساب",
  backHome: "العودة إلى الرئيسية",
  loginFailed: "فشل تسجيل الدخول.",
  heroTitle: "دقة تشغيلية على نطاق واسع",
  heroText: "خطط ونفّذ نقلات الحفارات عبر لوجستيات مدفوعة بالمحاكاة ورؤية تشغيلية كاملة.",
  openWorkspace: "فتح مساحة العمل",
  digitizeNow: "ابدأ الرقمنة",
  featuresTitle: "المزايا",
  featuresHeadline: "برنامج عمليات مصمم لوضوح النقل",
  aboutTitle: "من نحن",
  aboutHeadline: "مصمم للفرق التي تحتاج السرعة دون فقدان السيطرة",
  aboutCopy: "يحافظ RigSync على اللغة البصرية الداكنة لغرفة القيادة في المنتج الحالي مع تحويلها إلى واجهة تشغيلية قابلة للتوسع. التجربة مهيأة للتخطيط قبل النقل ولوحات متابعة واضحة وقراءة موثوقة على سطح المكتب والجهاز اللوحي.",
  rigMovesTracked: "نقلات حفارات متتبعة",
  savedOperationalRuns: "تشغيلات محفوظة",
  logicalLoads: "الأحمال المنطقية",
  availableForPlanning: "متاحة للتخطيط",
  routingMode: "وضع المسار",
  liveFallback: "حي + بديل",
  resilientDefault: "مرن افتراضياً",
  footerCopy: "واجهة SaaS متميزة لعمليات نقل الحفارات الحديثة من التخطيط حتى التنفيذ.",
  product: "المنتج",
  company: "الشركة",
  dashboard: "لوحة التحكم",
  assignedRig: "الحفارة المخصصة",
  rigDrillingOverview: "نظرة عامة على الحفارة",
  currentSite: "الموقع الحالي",
  assignedField: "الحقل المخصص",
  currentWell: "البئر الحالي",
  drillingCompletion: "نسبة الحفر",
  currentWellProgress: "تقدم البئر الحالي",
  reusableStock: "المخزون القابل لإعادة الاستخدام",
  loadGroupsOnSite: "مجموعات أحمال في الموقع",
  startupLoadsReady: "أحمال البدء الجاهزة",
  stillMissing: "ما يزال مفقوداً",
  fleetAvailable: "الأسطول المتاح",
  managerTrucksFree: "شاحنات المدير المتاحة للتخصيص",
  neededLoadsOnSite: "الأحمال المطلوبة في الموقع",
  cancel: "إلغاء",
  saveLoads: "حفظ الأحمال",
  editLoads: "تعديل الأحمال",
  reusableLoadsAdjust: "يمكن تعديل الأحمال المطلوبة القابلة لإعادة الاستخدام فقط هنا. أحمال الحفارة الدائمة تبقى للقراءة فقط.",
  editable: "قابل للتعديل",
  onSite: "في الموقع",
  truck: "الشاحنة",
  needed: "المطلوب",
  countOnSite: "العدد في الموقع",
  availableToTransfer: "المتاح للنقل",
  planned: "مخطط",
  noReusableLoads: "لا توجد أحمال مطلوبة قابلة لإعادة الاستخدام لهذه الحفارة.",
  currentRigMove: "نقلة الحفارة الحالية",
  execution: "التنفيذ",
  completion: "الإنجاز",
  managerView: "عرض المدير",
  supervisor: "المشرف",
  managerOverview: "نظرة عامة للمدير",
  rigOperations: "عمليات حفارات",
  managerOverviewCopy: "العمليات الحية والشاحنات الجاهزة وحسابات السائقين في شاشة واحدة.",
  drillingRigs: "حفارات في الحفر",
  alreadyOperating: "تعمل حالياً",
  movingRigs: "حفارات تتحرك",
  executingNow: "قيد التنفيذ الآن",
  planningRigs: "حفارات في التخطيط",
  stillPlanning: "ما زالت في التخطيط",
  totalLoads: "إجمالي الأحمال",
  acrossAllMoves: "عبر جميع النقلات",
  driversReady: "السائقون الجاهزون",
  driverAccounts: "حسابات سائقين",
  driverCapacity: "سعة السائقين",
  currentlyAllocated: "مخصصة حالياً",
  activeDrivers: "السائقون النشطون",
  linkedToLiveTasks: "مرتبطون بمهام حية",
  foremenActive: "الفورمن النشطون",
  totalForemen: "إجمالي الفورمن",
  resources: "الموارد",
  trucksReady: "شاحنات جاهزة",
  resourcesCopy: "أنشئ حسابات السائقين فقط. كل سائق يحمل نوع شاحنته، ويستخدم المخطط ذلك كشاحنة مخصصة للسائق.",
  closeDriver: "إغلاق السائق",
  addDriver: "إضافة سائق",
  availableDrivers: "السائقون المتاحون",
  tasksWaiting: "المهام المنتظرة",
  driverAppSyncTarget: "هدف مزامنة تطبيق السائق",
  driverName: "اسم السائق",
  remove: "إزالة",
  assigned: "مخصص",
  available: "متاح",
  liveTask: "مهمة حية",
  taskObject: "كائن المهمة",
  driverTruck: "شاحنة السائق",
  currentTrip: "الرحلة الحالية",
  moreTripsQueued: "رحلات أخرى في الانتظار بعد هذه الرحلة.",
  assignedTrips: "الرحلات المخصصة",
  driverOverview: "نظرة عامة للسائق",
  activeTasks: "مهام نشطة",
  completeAssignedTask: "أكمل كل مهمة مخصصة بالترتيب: فك الحفارة ثم النقل ثم التركيب.",
  rigDown: "فك الحفارة",
  rigMove: "نقل الحفارة",
  rigUp: "تركيب الحفارة",
  completed: "مكتمل",
  queued: "في الانتظار",
  route: "المسار",
  pending: "قيد الانتظار",
  done: "تم",
  noAssignedTrips: "لا توجد رحلات مخصصة بعد. ستظهر الرحلات بعد أن يبدأ الفورمن التنفيذ.",
  timePassed: "الوقت المنقضي",
  planByNow: "المخطط حتى الآن",
  nextTask: "المهمة التالية",
  executionTracking: "متابعة التنفيذ",
  actualVsPlanned: "الفعلي مقابل المخطط",
  aheadBehind: "متقدم / متأخر",
  timeLeft: "الوقت المتبقي",
  driversAssigned: "السائقون المخصصون",
  tasksDone: "المهام المنجزة",
  stageTasksDone: "مهام المراحل المنجزة",
  plannedTasksByNow: "المهام المخططة حتى الآن",
  plannedTasks: "المهام المخططة",
  executionPlan: "خطة التنفيذ",
  customExecutionPlan: "خطة تنفيذ مخصصة",
  planOverview: "نظرة عامة على الخطة",
  totalTime: "إجمالي الوقت",
  roundTrips: "الرحلات",
  planCost: "تكلفة الخطة",
  criticalPath: "المسار الحرج",
  homeHeroTitleLine1: "الدقة التشغيلية",
  homeHeroTitleAccent: "المحكمة",
  homeHeroTitleLine2: "على نطاق واسع",
  homeHeroBody: "خطط ونفّذ نقلات الحفارات عبر شبكة تشغيلية مترابطة واحدة. يربط RigSync الحفارات والمسارات والشاحنات وقرارات الميدان داخل نظام بصري حي يتحرك مع الصفحة مثل سطح تحكم تفاعلي.",
  homeAboutBadge: "عن RigSync",
  homeAboutTitle: "توأم رقمي مبني لقرارات نقل الحفارات الحقيقية",
  homeAboutBody: "يمنح RigSync شركات الحفر توأماً رقمياً لعمليات نقلها. بدلاً من تنسيق النقلات عبر جداول منفصلة واتصالات هاتفية وأدوات متابعة معزولة، يمكن للفرق نمذجة الحفارات والشاحنات والسائقين والمسارات والموارد وجاهزية الموقع داخل نظام تشغيلي واحد. النتيجة هي تخطيط أسرع ومفاضلات أوضح ورؤية تنفيذ أقوى وتحكم أفضل من المكتب إلى الميدان.",
  homeMetricConnectedRigsLabel: "حفارات مترابطة",
  homeMetricConnectedRigsMeta: "عبر شبكة الشركة",
  homeMetricMoveScenariosLabel: "سيناريوهات النقل",
  homeMetricMoveScenariosMeta: "مفاضلات السرعة والتكلفة والاستغلال",
  homeMetricTrackedResourcesLabel: "موارد متتبعة",
  homeMetricTrackedResourcesLoadingMeta: "جارٍ تحميل الإجماليات التشغيلية الحية",
  homeMetricTrackedResourcesMeta: "السائقون والشاحنات والأحمال وإشارات الجاهزية",
  homeMetricExecutionViewsLabel: "واجهات التنفيذ",
  homeMetricExecutionViewsMeta: "التخطيط وتتبع النقل والإشراف والمساعدة الذكية",
  homeFeaturesTitle: "من تخطيط النقلة إلى الإشراف على الأسطول في نظام واحد",
  homeFeaturesLead: "يجمع RigSync التخطيط والتنفيذ ورؤية الأسطول وجاهزية الميدان داخل نظام تشغيلي واحد مبني للتحكم الحي في نقل الحفارات.",
  homeFeaturePlanningTitle: "تخطيط الحفارات عبر الشبكة",
  homeFeaturePlanningCopy: "اعرض أسطول الشركة كشبكة تشغيلية مترابطة واحدة، واختر الحفارة التي تحتاج إلى النقل، وخطط ضمن سياق الحفارات والمسارات والشاحنات والقيود الميدانية المتاحة.",
  homeFeatureOptimizationTitle: "تحسين واعٍ بالمفاضلات",
  homeFeatureOptimizationCopy: "قارن أفضل خطة نقل من حيث السرعة أو التكلفة أو الاستغلال. يعرض RigSync المفاضلات التشغيلية بوضوح حتى تتوافق الخطة المختارة مع الواقع الميداني.",
  homeFeatureExecutionTitle: "واجهة تنفيذ التوأم الرقمي",
  homeFeatureExecutionCopy: "انتقل من التخطيط إلى التنفيذ على نفس التوأم التشغيلي. تابع تقدم المسار ومراحل النقلة والشاحنات النشطة وجاهزية الموقع دون التنقل بين أدوات منفصلة.",
  homeFeatureOversightTitle: "إشراف مكتبي على مستوى الأسطول",
  homeFeatureOversightCopy: "أشرف على جميع الحفارات والنقلات النشطة والسائقين والشاحنات والموارد الميدانية من سطح تحكم واحد مصمم لإظهار رؤية الإدارة عبر شبكة الشركة كاملة.",
  homeFeatureResourcesTitle: "التحكم في الموارد والسائقين",
  homeFeatureResourcesCopy: "أدر جاهزية الشاحنات والسائقين المرتبطين وتوفر الأسطول والتكليفات التشغيلية من خلال مساحة عمل واحدة تبقى متوافقة مع تنفيذ النقلة.",
  homeFeatureAssistantTitle: "مساعد تشغيلي بالذكاء الاصطناعي",
  homeFeatureAssistantCopy: "استخدم المساعد لاسترجاع حالة النقلة ومراجعة مفاضلات الخطط ودعم المراجعة العليا والإجابة بسرعة عن الأسئلة التشغيلية مع وجود السياق الصحيح داخل النظام.",
  homeFaqTitle: "أسئلة التوأم الرقمي المهمة",
  homeFaq1Question: "ما الفرق بين التوأم الرقمي والمحاكاة؟",
  homeFaq1Answer: "المحاكاة تختبر سيناريو نقل واحداً محتملاً. أما التوأم الرقمي فهو أوسع، إذ يمثل النظام التشغيلي الحي نفسه بما يشمل الحفارات والشاحنات والسائقين والمسارات والموارد وحالة النقلة. في RigSync تمثل المحاكاة قدرة واحدة داخل التوأم الرقمي.",
  homeFaq2Question: "لماذا أستخدم RigSync بدلاً من أدوات التخطيط التقليدية؟",
  homeFaq2Answer: "غالباً ما يكون تخطيط نقل الحفارات التقليدي مجزأً بين الجداول والاتصالات والخطط الثابتة وأدوات التتبع المنفصلة. يجمع RigSync التخطيط والمقارنة ورؤية التنفيذ والإشراف المكتبي والذكاء التشغيلي في منصة مترابطة واحدة.",
  homeFaq3Question: "كيف يساعد RigSync في القرارات أثناء النقلة؟",
  homeFaq3Answer: "يساعد RigSync الفرق على اختيار الخطة الأنسب للأولوية الحالية، سواء كانت السرعة أو خفض التكلفة أو تحسين استغلال الشاحنات. وأثناء التنفيذ يحافظ على توافق المديرين والفورمن وفرق الميدان على صورة تشغيلية واحدة.",
  homeFooterBody: "منصة توأم رقمي لتخطيط نقل الحفارات على مستوى الشبكة، والإشراف على التنفيذ، والذكاء التشغيلي.",
  homeFooterTagline: "مبني لعمليات نقل الحفارات بالتوأم الرقمي",
  allRigs: "كل الحفارات",
  arrivalLockedOutbound: "يبقى تأكيد الوصول مقفلاً حتى تصل قراءة المستشعر الحي إلى 100%.",
  arrivalLockedReturn: "يبقى تأكيد الوصول مقفلاً حتى تصل قراءة المستشعر الحي إلى 100%.",
  arrived: "تم الوصول",
  arrivedSource: "تم الوصول إلى المصدر",
  assignedTrip: "الرحلة المخصصة",
  averageCompletion: "متوسط الإنجاز",
  close: "إغلاق",
  closedDriverTasks: "مهام السائق المغلقة",
  completedTasks: "المهام المكتملة",
  delayMinutesToday: "دقائق التأخير اليوم",
  delayReason: "سبب التأخير",
  delayReasonNeeded: "سبب التأخير مطلوب",
  delayReasonPlaceholder: "ازدحام، مشكلة في الحفارة، طقس، تأخير في التحميل...",
  delayReasonPrompt: "أضف سبباً إذا كانت هذه المرحلة متأخرة.",
  delayReasonPromptDemo: "أضف سبباً إذا كانت هذه المرحلة متأخرة في العرض الحي.",
  delayReasonRequired: "أدخل سبب التأخير عندما تتجاوز المرحلة 20 دقيقة تأخيراً.",
  delayReasonRequiredDemo: "أدخل سبب التأخير عندما تتجاوز المرحلة 20 ثانية تأخيراً.",
  destination: "الوجهة",
  drilling: "الحفر",
  driver: "السائق",
  driverMoveComplete: "اكتملت رحلة العودة.",
  driverMoveOutbound: "الشاحنة في رحلة الذهاب إلى الحفارة.",
  driverMoveReadyReturn: "وصلت الشاحنة إلى الحفارة. ابدأ العودة بمجرد إنزال الحمولة.",
  driverMoveReturning: "الشاحنة تعود إلى المصدر. أكد الوصول فقط عند عودتها فعلاً إلى المصدر.",
  driverMoveWaitingStart: "الشاحنة متوقفة عند المصدر. ابدأ الحركة عندما يغادر السائق.",
  driverReadiness: "جاهزية السائقين",
  driverReturnRunning: "الشاحنة الفارغة تعود إلى المصدر. أكد الوصول فقط عندما تعود فعلاً إلى المصدر.",
  driverReturnWaitingStart: "الشاحنة الفارغة متوقفة عند الوجهة. ابدأ العودة عندما يغادر السائق.",
  driverTasks: "مهام السائق",
  eta: "الوقت المتوقع للوصول",
  fleetReady: "جاهزية الأسطول",
  futureStepsLocked: "الخطوات التالية تبقى مقفلة حتى تكتمل الخطوة الحالية.",
  inDrilling: "في الحفر",
  late: "متأخر",
  lateBy: "متأخر بمقدار",
  left: "متبقٍ",
  liveTracking: "تتبع حي",
  loadTransfers: "نقل الأحمال",
  loads: "الأحمال",
  locked: "مقفل",
  managerNetwork: "شبكة المدير",
  managerPlanOverview: "نظرة المدير على الخطة",
  min: "د",
  move: "نقل",
  networkSummary: "ملخص الشبكة",
  noRigSelected: "لم يتم اختيار حفارة",
  noRigSelectedCopy: "اختر حفارة على الخريطة لفحص حالتها الحية وجاهزية المسار وحالة النقل.",
  noRigSelectedCopy3d: "اختر حفارة في العرض ثلاثي الأبعاد لفحص حالتها الحية وجاهزية المسار وحالة النقل.",
  pausedVsPlan: "متوقف مؤقتاً مقابل الخطة",
  phaseEta: "الوقت المتوقع للمرحلة",
  planWindow: "نافذة الخطة",
  planning: "التخطيط",
  progress: "التقدم",
  readyForDispatch: "جاهز للانطلاق",
  readyToFinish: "جاهز للإنهاء",
  readyToTransport: "جاهز للنقل",
  rigOnSite: "الحفارة في الموقع",
  rigOnSiteCopy: "الحفارة الوجهة موجودة بالفعل في الموقع وليست في نقل نشط.",
  rigsLive: "حفارات حية",
  routeReady: "المسار جاهز",
  routeReadyCopy: "المسار مجهز والحفارة جاهزة للنقل.",
  routesTracked: "المسارات المتتبعة",
  selectedRig: "الحفارة المحددة",
  sensor: "المستشعر",
  source: "المصدر",
  startMoving: "ابدأ الحركة",
  startReturn: "ابدأ العودة",
  status: "الحالة",
  taskCompletion: "إنجاز المهام",
  totalRigs: "إجمالي الحفارات",
  transferInMotion: "النقل جارٍ",
  transferInMotionCopy: "هذه الحفارة تُنقل حالياً.",
  transferLoad: "حمولة نقل",
  trip: "رحلة",
  truckType: "نوع الشاحنة",
  trucksFreeToAssign: "شاحنات متاحة للتخصيص",
  viewAll: "عرض الكل",
  waitingOnFirstStage: "بانتظار المرحلة الأولى",
};

const MESSAGES = { en, ar };

const EXTRA_PHRASE_TRANSLATIONS = {
  ar: {
    "About RigSync": "عن RigSync",
    "Active rigs today": "الحفارات النشطة اليوم",
    "Add Foreman": "إضافة فورمن",
    "Add Truck": "إضافة شاحنة",
    "Add Truck And Driver": "إضافة شاحنة وسائق",
    "Assigned fleet summary for this rig.": "ملخص الأسطول المخصص لهذه الحفارة.",
    "Beginning of shift": "بداية الوردية",
    "Close Foreman": "إغلاق الفورمن",
    "Create Foreman": "إنشاء فورمن",
    "Create a managed truck together with its linked driver account.": "أنشئ شاحنة مُدارة مع حساب السائق المرتبط بها.",
    "Created At": "تاريخ الإنشاء",
    "Control room": "غرفة التحكم",
    "Current day estimate": "تقدير اليوم الحالي",
    "Current Rig Location": "موقع الحفارة الحالي",
    "Current site | Not set": "الموقع الحالي | غير محدد",
    "Data issue": "مشكلة بيانات",
    "Delay Events": "أحداث التأخير",
    "Delay Minutes": "دقائق التأخير",
    "Delete Move": "حذف النقلة",
    "Delete move": "حذف النقلة",
    "Driver email": "بريد السائق",
    "Driver": "السائق",
    "End of shift": "نهاية الوردية",
    "Execution Alerts": "تنبيهات التنفيذ",
    "Field Leads": "قادة الميدان",
    "Field Leads, set their current rig, and track what each foreman is handling.": "أضف قادة الميدان وحدد حفارتهم الحالية وتابع ما يديره كل فورمن.",
    "Final closeout": "الإقفال النهائي",
    "Finished assignment tasks across tracked moves": "المهام المكتملة عبر النقلات المتتبعة",
    "Fleet Mix Chart": "مخطط توزيع الأسطول",
    "Fleet Utilization Timeline": "الجدول الزمني لاستغلال الأسطول",
    "Fleet units": "وحدات الأسطول",
    "Generated At": "تم الإنشاء في",
    "Loading 3D view": "جارٍ تحميل العرض ثلاثي الأبعاد",
    "Loading dashboard": "جارٍ تحميل لوحة التحكم",
    "Loading live data": "جارٍ تحميل البيانات الحية",
    "Loading move": "جارٍ تحميل النقلة",
    "Loading report data": "جارٍ تحميل بيانات التقارير",
    "Loading reports": "جارٍ تحميل التقارير",
    "Loading rig move": "جارٍ تحميل نقلة الحفارة",
    "Latest Reason": "أحدث سبب",
    "Latest Reason | No issue recorded.": "أحدث سبب | لم يتم تسجيل مشكلة.",
    "Latest Log": "آخر سجل",
    "Foreman": "الفورمن",
    "Manager": "المدير",
    "Manager Notified": "تم إشعار المدير",
    "Move unavailable": "النقلة غير متاحة",
    "Move unavailable | Return to the dashboard and choose another rig move.": "النقلة غير متاحة | ارجع إلى لوحة التحكم واختر نقلة حفارة أخرى.",
    "No active foreman": "لا يوجد فورمن نشط",
    "No active rig move right now.": "لا توجد نقلة حفارة نشطة حالياً.",
    "No current move": "لا توجد نقلة حالية",
    "No delay reason recorded.": "لم يتم تسجيل سبب للتأخير.",
    "No driver linked": "لا يوجد سائق مرتبط",
    "No events yet.": "لا توجد أحداث بعد.",
    "No issue recorded.": "لم يتم تسجيل مشكلة.",
    "No live move": "لا توجد نقلة حية",
    "No live event yet": "لا يوجد حدث حي بعد",
    "No rig move history yet.": "لا يوجد سجل نقلات للحفارة بعد.",
    "No trucks are currently available in the manager fleet for a new rig move.": "لا توجد شاحنات متاحة حالياً في أسطول المدير لنقلة حفارة جديدة.",
    "Planning Engine": "محرك التخطيط",
    "Please allow popups to print this report.": "يرجى السماح بالنوافذ المنبثقة لطباعة هذا التقرير.",
    "Remaining Assignments": "التكليفات المتبقية",
    "Remaining Tasks": "المهام المتبقية",
    "Report": "تقرير",
    "Request Rig Move": "طلب نقلة حفارة",
    "Reserved and active | Planning only": "محجوزة ونشطة | للتخطيط فقط",
    "Restoring the saved move from the database.": "جارٍ استعادة النقلة المحفوظة من قاعدة البيانات.",
    "Return to the dashboard and choose another rig move.": "ارجع إلى لوحة التحكم واختر نقلة حفارة أخرى.",
    "Rig move not found": "لم يتم العثور على نقلة الحفارة",
    "Search truck, move, destination": "ابحث عن شاحنة أو نقلة أو وجهة",
    "Select a destination location.": "اختر موقع الوجهة.",
    "Select current rig location": "اختر موقع الحفارة الحالي",
    "Select destination": "اختر الوجهة",
    "Shift end": "نهاية الوردية",
    "Shift start": "بداية الوردية",
    "Start Date": "تاريخ البدء",
    "Start Day": "يوم البدء",
    "The selected move is no longer available.": "النقلة المحددة لم تعد متاحة.",
    "Track the assigned rig, live move state, and drilling readiness.": "تابع الحفارة المخصصة وحالة النقلة الحية وجاهزية الحفر.",
    "Tracking Status": "حالة التتبع",
    "Trucks Available": "الشاحنات المتاحة",
    "Trucks Reserved": "الشاحنات المحجوزة",
    "Waiting for execution": "بانتظار التنفيذ",
    "Waiting for first rig move": "بانتظار أول نقلة حفارة",
    "Waiting for the latest moves and manager resources from Firebase.": "بانتظار أحدث النقلات وموارد المدير من Firebase.",
    "Waiting for the latest moves and resources from the backend.": "بانتظار أحدث النقلات والموارد من الخلفية.",
    "Where the fleet is being used right now across active rig moves.": "أين يتم استخدام الأسطول حالياً عبر نقلات الحفارات النشطة.",
  },
};

const PHRASE_TRANSLATIONS = {
  en: {},
  ar: {
    ...Object.fromEntries(Object.keys(en).map((key) => [en[key], ar[key]])),
    ...EXTRA_PHRASE_TRANSLATIONS.ar,
  },
};

const NORMALIZED_PHRASE_TRANSLATIONS = Object.fromEntries(
  Object.entries(PHRASE_TRANSLATIONS).map(([language, entries]) => [
    language,
    Object.fromEntries(
      Object.entries(entries).map(([phrase, value]) => [phrase.toLowerCase(), value]),
    ),
  ]),
);

export function getLanguageDirection(language = DEFAULT_LANGUAGE) {
  return language === "ar" ? "rtl" : "ltr";
}

export function translatePhrase(language = DEFAULT_LANGUAGE, phrase = "") {
  if (!phrase || language === DEFAULT_LANGUAGE) {
    return phrase;
  }

  const rawPhrase = String(phrase);
  const trimmedPhrase = rawPhrase.trim();
  const findTranslation = (value) => {
    if (!value) {
      return "";
    }
    return (
      PHRASE_TRANSLATIONS[language]?.[value] ||
      NORMALIZED_PHRASE_TRANSLATIONS[language]?.[value.toLowerCase()] ||
      ""
    );
  };
  const translateComposite = (value) => {
    const direct = findTranslation(value);
    if (direct) {
      return direct;
    }

    for (const separator of [" | ", " • ", " / "]) {
      if (!value.includes(separator)) {
        continue;
      }
      return value
        .split(separator)
        .map((part) => translateComposite(part.trim()))
        .join(separator);
    }

    return value;
  };
  const exactTranslation = findTranslation(rawPhrase);
  if (exactTranslation) {
    return exactTranslation;
  }

  const trimmedTranslation = translateComposite(trimmedPhrase);
  if (!trimmedTranslation) {
    return rawPhrase;
  }

  const prefixLength = rawPhrase.indexOf(trimmedPhrase);
  const suffixLength = rawPhrase.length - prefixLength - trimmedPhrase.length;
  return `${rawPhrase.slice(0, prefixLength)}${trimmedTranslation}${rawPhrase.slice(rawPhrase.length - suffixLength)}`;
}

export function translate(language = DEFAULT_LANGUAGE, key, fallback = "") {
  const value = MESSAGES[language]?.[key] || MESSAGES[DEFAULT_LANGUAGE]?.[key];
  if (value) {
    return value;
  }

  const resolvedFallback = fallback || key || "";
  return translatePhrase(language, resolvedFallback);
}
